### ISSUE TITLE
有web开发的试卷嘛~

### ISSUE THREAD

**Issue by sjyjytu** [lingxu-wxw/SE_Notes#1]
你好，请问有web开发的卷子嘛~~~~

**Comment by fyc1007261** [comment]
木有。。建议对着自己做的项目，想一下用到每个框架/模块（spring, ajax, etc.)的作用、优缺点以及为什么这么设计，基本就不会有太大问题了。真写不出来就写为了解耦hhh

**Comment by sjyjytu** [comment]
哈哈哈哈哈哈哈哈哈哈，好的，谢谢~~~

**Comment by lingxu-wxw** [comment]
close issue
